version: "3.3"

services:


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka:${VERSION}
    ports:
      - "9092:9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_HOST_NAME: "localhost:9092"

  kafka2:
    image: wurstmeister/kafka:${VERSION}
    ports:
      - "9093:9093"
    environment:
      KAFKA_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9093"
      KAFKA_ADVERTISED_PORT: "9093"
      KAFKA_ADVERTISED_HOST_NAME: "localhost:9093"

  kafka3:
    image: wurstmeister/kafka:${VERSION}
    ports:
      - "9094:9094"
    environment:
      KAFKA_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9094"
      KAFKA_ADVERTISED_PORT: "9094"
      KAFKA_ADVERTISED_HOST_NAME: "localhost:9094"
